### PR TITLE
add interactive boot menu description

### PR DESCRIPTION
**Pull request by WinnieXU1**
1. add the description of how to enable an interactive boot menu by parameter "menu".
2. provide a link where there is a bios file which supports the boot menu.

### CODE REVIEW

**Comment by WinnieXU1** [comment]
@fub2 @turtle-fly could you please help me review it？ 🌞

**Comment by turtle-fly** [comment]
@WinnieXU1 please add how user use the bintray binary as well.

**Comment by WinnieXU1** [comment]
Thank you~@turtle-fly I have added~

**Comment by fub2** [comment]
+1

**Pull request merged**
